### ISSUE TITLE
Bundle Does Not Work In Atom & Sublime Text

### ISSUE THREAD

**Issue by dominicap** [textmate/swift.tmbundle#29] opened 2016-12-28 23:54 UTC
When trying to use this bundle in Atom or Sublime, it does not work.

In Atom, after converting the package through Atom’s package manager with the command, ``` apm init --package language-swift --convert https://github.com/textmate/swift.tmbundle ```, moving it to Atom's packages directory and opening a swift file, I receive a “Uncaught Error: invalid pattern in look-behind” and I cannot type at all in the file.

In Sublime Text 2, after moving the bundle to the packages directory, I receive a "Error loading syntax file "Packages/swift.tmbundle/Syntaxes/Swift.tmLanguage”: Unexpected capture value" and syntax highlighting, snippets etc. do not work.

In Sublime Text 3, after moving the bundle to the packages directory, Sublime does not even acknowledge the package.

It would be appreciated if this could be addressed as it is, as far as I can tell, the most complete and up to date package for swift support in other textmate and other editors.

**Comment by jtbandes** [comment] 2016-12-29 03:08
Can you tell which regular expressions are causing the problem?

**Comment by infininight** [comment] 2016-12-29 10:24
@dominicap The Atom syntax format is almost entirely compatible, there is only some minor regex syntax differences that can easily be worked around. So this is something we can correct if someone can narrow down the rule that is at fault.

Sublime is not going to work. It does not support TextMate 2 grammars, there are vast differences and it is not something we will be correcting.

**Comment by dominicap** [comment] 2016-12-29 15:21
@jtbandes Atom does not explicitly state which line/expression causes the problem. However, I narrowed it down to the following snippet of code in Swift.tmLanguage:
```xml
<dict>
    <key>match</key>
    <string>(?&lt;=\bProcess\.|\bCommandLine\.)(arguments|argc|unsafeArgv)</string>
    <key>name</key>
    <string>support.variable.swift</string>
</dict>
```
This is the converted CoffeeScript version. If this segment is commented out, errors are not thrown

```coffeescript
{
  match: "(?<=\\bProcess\\.|\\bCommandLine\\.)(arguments|argc|unsafeArgv)"
  name: "support.variable.swift"
}
```

**Comment by svanimpe** [comment] 2018-01-25 09:11
Visual Studio Code also crashes on that same regular expression. There seem to be minor incompatibilities between the versions of Onigurama used in these editors.

The issue seems to be the word break `\b` in the look-behind pattern. If I remove that, the pattern is accepted (although it won't work as intended). Does anyone know if this should be valid?

**Comment by jtbandes** [comment] 2018-04-23 02:15
I think I simply forgot to close this issue. The problem should be fixed now!

**Closed by jtbandes** 2018-04-23 02:15 UTC
